FROM continuumio/anaconda3
RUN pip install gdown && \
	cd /home && gdown https://drive.google.com/uc?id=18jtKeWe6SEy0ypvNiiFTJvtBN6kgdShc && \
	apt update && apt install -y p7zip-full ffmpeg libsm6 libxext6 && apt-get clean && \
	7z x simswap-v24-11-2021.7z && rm simswap-v24-11-2021.7z && \
	cd simswap-main
SHELL ["/bin/bash", "-c"]
RUN	conda create -n simswap python=3.6 -y && source ~/.bashrc && conda activate simswap && \
    	conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch -y && conda clean -a -y && \
	pip install --ignore-installed imageio && \
	pip install insightface==0.2.1 onnxruntime moviepy && pip cache purge
RUN sed -i 's/base/simswap/' ~/.bashrc
WORKDIR /home/simswap-main
